name: Deploy Theme BD24
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build assets
        run: npm run build

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H innof.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -avz --delete \
          --exclude='.git*' \
          --exclude='node_modules' \
          --exclude='package*.json' \
          --exclude='.env*' \
          --exclude='README.md' \
          --exclude='*.config.js' \
          --exclude='tests' \
          -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          ./ sumon@innof.com:/var/www/bangla24/wp-content/themes/bangla24v2/

      - name: Set Permissions
        run: |
          ssh -i ~/.ssh/id_ed25519 sumon@innof.com "cd /var/www/bangla24/wp-content/themes/bangla24v2/ && \
          sudo chown -R www-data:www-data . && \
          sudo chmod -R 755 . && \
          sudo find . -type f -exec chmod 644 {} \;"