name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r * deploy/
          rm -rf deploy/node_modules deploy/tests deploy/.git deploy/.github
          rm -f deploy/.gitignore deploy/README.md deploy/package.json deploy/package-lock.json deploy/tailwind.config.js deploy/postcss.config.js

      - name: Deploy to Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: innof.com
          username: sumon
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: ./deploy/
          scp_target: /var/www/bangla24/wp-content/themes/bangla24v2/
          before_script: |
            rm -rf /var/www/bangla24/wp-content/themes/bangla24v2/*
          after_script: |
            cd /var/www/bangla24/wp-content/themes/bangla24v2/
            rm -rf .git .github
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -r -P 22 --exclude=node_modules --exclude=tests --exclude=.gitignore --exclude=README.md --exclude=package.json --exclude=package-lock.json --exclude=tailwind.config.js --exclude=postcss.config.js --exclude=.git --exclude=.github
