name: Deploy Theme BD24
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build assets
        run: npm run build

      - name: Deploy via Rsync
        uses: appleboy/ssh-action@v1.8.0
        with:
          host: innof.com
          username: sumon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -avz --delete \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.github \
            --exclude=tests \
            --exclude=.gitignore \
            --exclude=README.md \
            --exclude=package.json \
            --exclude=package-lock.json \
            --exclude=tailwind.config.js \
            --exclude=postcss.config.js \
            ${{ github.workspace }}/ /var/www/bangla24/wp-content/themes/bangla24v2/