name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REMOTE_HOST }}
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            --exclude=/.git/ \
            --exclude=/.github/ \
            --exclude=/node_modules/ \
            --exclude=/tests/ \
            --exclude=.gitignore \
            --exclude=README.md \
            --exclude=package.json \
            --exclude=package-lock.json \
            ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/bangla24/wp-content/themes/bangla24v2/
