name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/bangla24/wp-content/themes/
            rm -rf bangla24v2
            mkdir -p bangla24v2
            cd bangla24v2
            git clone https://github.com/${{ github.repository }}.git .
            rm -rf .git .github node_modules tests
            rm .gitignore README.md package.json package-lock.json
