name: Deploy Theme BD24
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Cache node_modules for faster installs

      - name: Install dependencies
        run: npm ci --prefer-offline  # Clean install using cached modules

      - name: Build assets
        run: npm run build

      - name: Deploy via Rsync
        uses: appleboy/ssh-action@v1.8.0
        with:
          host: innof.com
          username: sumon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/bangla24/wp-content/themes/bangla24v2/
            rsync -avz --delete --exclude={'node_modules','.git','.github','tests'} \
            -e "ssh -p 22 -o StrictHostKeyChecking=no" \
            $GITHUB_WORKSPACE/ sumon@innof.com:/var/www/bangla24/wp-content/themes/bangla24v2/