name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build

      - name: Prepare deployment files
        run: |
          rm -rf deploy-temp
          mkdir deploy-temp
          rsync -av --progress ./ ./deploy-temp/ --exclude deploy-temp --exclude node_modules --exclude tests --exclude .git --exclude .github --exclude .gitignore --exclude README.md --exclude package.json --exclude package-lock.json --exclude tailwind.config.js --exclude postcss.config.js

      - name: Deploy to Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: innof.com
          username: sumon
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: ./deploy-temp/
          scp_target: /var/www/bangla24/wp-content/themes/bangla24v2/
          before_script: |
            rm -rf /var/www/bangla24/wp-content/themes/bangla24v2/*
