name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build
        
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude=/.git/ --exclude=/.github/ --exclude=/node_modules/ --exclude=/tests/ --exclude=.gitignore --exclude=README.md --exclude=package.json --exclude=package-lock.json
          path: ./
          remote_path: /var/www/bangla24/wp-content/themes/bangla24v2/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
