name: Deploy Theme BD24
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build

      - name: Deploy to Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: innof.com
          username: sumon
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: ./
          scp_target: /var/www/bangla24/wp-content/themes/bangla24v2/
          before_script: |
            rm -rf /var/www/bangla24/wp-content/themes/bangla24v2/*
          after_script: |
            cd /var/www/bangla24/wp-content/themes/bangla24v2/
            rm -rf .git .github node_modules tests .gitignore README.md package.json package-lock.json
