name: Deploy Theme
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build assets
        run: npm run build
        
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          TARGET: "~/../../var/www/bangla24/wp-content/themes/bangla24v2/"
          EXCLUDE: "/.git/, /.github/, /node_modules/, /tests/, .gitignore, README.md, package.json, package-lock.json"
          SCRIPT_BEFORE: |
            whoami
            pwd
          SCRIPT_AFTER: |
            echo "Deployment complete"
